objects/Donation__c.object
<CustomObject>
    <label>Donation</label>
    <nameField>
        <displayFormat>Donation-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Goods__c.object
<CustomObject>
    <fields>
        <fullName>Donation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Donation</label>
        <referenceTo>Donation__c</referenceTo>
        <relationshipLabel>Goods</relationshipLabel>
        <relationshipName>Goods</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Moving__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moving</label>
        <referenceTo>Goods_moving__c</referenceTo>
        <relationshipLabel>Goods</relationshipLabel>
        <relationshipName>Goods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NameOfProduct__c</fullName>
        <formula>Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name of product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Goods</relationshipLabel>
        <relationshipName>Goods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Goods</label>
    <nameField>
        <displayFormat>Good-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Goods_moving__c.object
<CustomObject>
    <fields>
        <fullName>Donation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Donation</label>
        <referenceTo>Donation__c</referenceTo>
        <relationshipLabel>Goods movings</relationshipLabel>
        <relationshipName>Goods_movings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FromStorage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From Storage</label>
        <referenceTo>Storage__c</referenceTo>
        <relationshipLabel>Goods movings</relationshipLabel>
        <relationshipName>Goods_movings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ToStorage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Storage</label>
        <referenceTo>Storage__c</referenceTo>
        <relationshipLabel>Goods movings (To Storage)</relationshipLabel>
        <relationshipName>Goods_movings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Goods movings</label>
    <nameField>
        <label>Goods movings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goods movings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Prod info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Storage__c.object
<CustomObject>
    <label>Storage</label>
    <nameField>
        <label>Storage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Storages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/StorageItems__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>StorageItems</relationshipLabel>
        <relationshipName>StorageItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Storage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Storage</label>
        <referenceTo>Storage__c</referenceTo>
        <relationshipLabel>StorageItems</relationshipLabel>
        <relationshipName>StorageItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>StorageItems</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StorageItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FromMovingToTotal.cls
public with sharing class FromMovingToTotal {

    public static void FromMovingToTotal(){
        List<Goods_moving__c> goodsRecords =[SELECT Id,FromStorage__c,Name,ToStorage__c, Donation__c FROM Goods_moving__c];
        for(Goods_moving__c good : goodsRecords){
            
            StorageItems__c[] item = [SELECT Name, Storage__c, Product__c, Quantity__c FROM StorageItems__c WHERE Storage__c =: good.ToStorage__c];
            if(item.size() >0){
                Goods__c quan = [SELECT Quantity__c, Donation__c FROM Goods__c WHERE Donation__c =: good.Donation__c];
                Decimal count =  quan.Quantity__c;
                item[0].Quantity__c += count;
                if((Decimal) item[0].Quantity__c <= 0){
                    delete  item[0];
                }
                else{
                    update item[0];
                }}
            else{
            
               	Goods__c[] goods = [SELECT NameOfProduct__c, Quantity__c FROM Goods__c WHERE Moving__c =: good.Id];
                if(goods.size()>0){
                String nameOfP = (String) goods[0].NameOfProduct__c;
                Decimal quantity = (Decimal) goods[0].Quantity__c;
                //Product__c product = [SELECT Name FROM Product__c WHERE Id =: (Id) nameOfP];
                StorageItems__c newItem = new StorageItems__c(
                Product__c = nameOfP,
                Quantity__c = quantity,
                Storage__c = good.ToStorage__c
                );
               insert newItem;
                }

            }

            
        }

    }
    
}